SELECT A.USER_ID, A.NICKNAME, W.SUM1 AS TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS SUM1
    FROM USED_GOODS_BOARD
    WHERE STATUS LIKE 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM1 >= 700000
) W 
JOIN USED_GOODS_USER A ON W.WRITER_ID = A.USER_ID
ORDER BY TOTAL_SALES;