WITH HourlyData AS (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HourOfDay
    FROM ANIMAL_OUTS
    WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
)
SELECT HourOfDay AS HOUR, COUNT(*) AS COUNT
FROM HourlyData
GROUP BY HourOfDay
ORDER BY HourOfDay;

