SELECT A.CATEGORY, SUM(B.SALES)
FROM BOOK A JOIN (SELECT * FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE,'%Y-%m-%d') LIKE '2022-01%') B ON A.BOOK_ID = B.BOOK_ID 
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY